version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "io.github.classgraph:classgraph"
      - dependency-name: "com.google.guava:*"